title: Curious Code - A Cloud, Data and Software Odyssey
description: Curious Code - A Cloud, Data and Software Odyssey
plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-pagination
  - jekyll-feed

exclude:
  - docker-compose.yml

sass:
  sass_dir: assets/css

excerpt_separator: <!--excerpt-above-->
future: true

feed:
  excerpt_only: true
  tags: true

paginate: 4
paginate_path: "/blog/page:num/"

responsive_image:
  template: _includes/imager-js.html
  sizes:
    - 320
    - 480
    - 800
