title: Soertszy's Cloud, Data and Software Blog
description: Soertszy's Cloud, Data and Software Blog
plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-pagination
exclude:
  - docker-compose.yml

sass:
  sass_dir: assets/css

excerpt_separator: <!--excerpt-above-->
future: true

paginate: 4
paginate_path: "/blog/page:num/"
